# App Engine Configuration for CloudCalc

runtime: nodejs16

env_variables:
  NODE_ENV: 'production'
  PORT: '8080'

handlers:
  - url: /.*
    script: auto
    secure: always

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  max_concurrent_requests: 50

network:
  session_affinity: true
